# Playstore Data Analysis

### importing library

In [3]:
import pandas as pd

- Pandas is a python library , used for data manupilation

### Loading Dataset

In [4]:
df=pd.read_csv("trial_data.csv")
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### Inspecting First 10 Rows Of The Dataset

In [5]:
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

- By using the command df.head(n),we can inspect the first n number of rows from the data set

In [6]:
df.tail(15)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,Varies with device,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10828,Manga-FR - Anime Vostfr,COMICS,3.4,291,13M,"10,000+",Free,0,Everyone,Comics,"May 15, 2017",2.0.1,4.0 and up
10829,Bulgarian French Dictionary Fr,BOOKS_AND_REFERENCE,4.6,603,7.4M,"10,000+",Free,0,Everyone,Books & Reference,"June 19, 2016",2.96,4.1 and up
10830,News Minecraft.fr,NEWS_AND_MAGAZINES,3.8,881,2.3M,"100,000+",Free,0,Everyone,News & Magazines,"January 20, 2014",1.5,1.6 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10832,FR Tides,WEATHER,3.8,1195,582k,"100,000+",Free,0,Everyone,Weather,"February 16, 2014",6,2.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

- also df.tail(n), can be used to inspect the last n number of rows

In [7]:
df.sample(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4019,Batmobile™ R/C Controller,FAMILY,3.7,452,30M,"100,000+",Free,0,Everyone,Entertainment,"February 2, 2018",1.0.8,4.4 and up
5585,Pacific Navy Fighter C.E. (AS),GAME,4.3,11379,20M,"500,000+",Free,0,Everyone 10+,Arcade,"July 29, 2018",1.4,4.0.3 and up
4597,T-Mobile DIGITS,COMMUNICATION,3.0,1820,33M,"100,000+",Free,0,Everyone,Communication,"February 15, 2018",1.1.50,4.4 and up

- df.sample(n) , this command brings n number of random rows

In [8]:
df.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

- df.dtypes , used to identify the datatypes from the dateset

In [9]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

<span style="color:#39FF14"><code>df.columns</code></span> → to display column names

In [10]:
df.shape

(10841, 13)

<span style="color:#39FF14"><code>df.shape</code></span> → displays number of rows and columns

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

#### from the above analysis we are able to identify the presence of missing values in various columns

-  1474 missung values in column "Rating"
- 1 missing value in column "type"
- 1 missing value in column "content rating"
- 7 missing values in column "current ver"
- 3 missing values in column "android ver"

### Selecting "Rating" Column

In [12]:
df['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

### Selecting Multiple columns

In [13]:
new = df[['Rating','Size',]]
new

       Rating                Size
0         4.1                 19M
1         3.9                 14M
2         4.7                8.7M
3         4.5                 25M
4         4.3                2.8M
...       ...                 ...
10836     4.5                 53M
10837     5.0                3.6M
10838     NaN                9.5M
10839     4.5  Varies with device
10840     4.5                 19M

[10841 rows x 2 columns]

### Filtering The Dataset

In [14]:
df[df['Rating']>4]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1,2.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

- filtered out apps, having  rating greater than 4

In [15]:
df[df['Category']=='FAMILY']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2014,YouTube Kids,FAMILY,4.5,470694,Varies with device,"50,000,000+",Free,0,Everyone,Entertainment;Music & Video,"August 3, 2018",3.43.3,4.1 and up
2015,Candy Bomb,FAMILY,4.4,42145,20M,"10,000,000+",Free,0,Everyone,Casual;Brain Games,"July 4, 2018",2.9.3181,4.0.3 and up
2016,ROBLOX,FAMILY,4.5,4449910,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
2017,Jewels Crush- Match 3 Puzzle,FAMILY,4.4,14774,19M,"1,000,000+",Free,0,Everyone,Casual;Brain Games,"July 23, 2018",1.9.3901,4.0.3 and up
2018,Coloring & Learn,FAMILY,4.4,12753,51M,"5,000,000+",Free,0,Everyone,Educational;Creativity,"July 17, 2018",1.49,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10821,Poop FR,FAMILY,NaN,6,2.5M,50+,Free,0,Everyone,Entertainment,"May 29, 2018",1,4.0.3 and up
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up

- Filterd apps that belongs to category "Family"

In [16]:
df[df['Genres']=='Education']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
700,TED,EDUCATION,4.6,181893,18M,"10,000,000+",Free,0,Everyone 10+,Education,"July 27, 2018",3.2.5,4.1 and up
701,English Communication - Learn English for Chin...,EDUCATION,4.7,2544,18M,"100,000+",Free,0,Everyone,Education,"December 29, 2017",3.1,4.0 and up
702,Khan Academy,EDUCATION,4.6,85375,21M,"5,000,000+",Free,0,Everyone,Education,"July 27, 2018",5.0.0,4.1 and up
703,Learn English with Wlingua,EDUCATION,4.7,314299,3.3M,"10,000,000+",Free,0,Everyone,Education,"May 2, 2018",1.94.9,4.0 and up
704,Ai La Trieu Phu - ALTP Free,EDUCATION,NaN,776,24M,"100,000+",Free,0,Everyone,Education,"July 23, 2018",1.5,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up

- filterd out apps that belongs to Genre "Education"

In [17]:
df[df['Last Updated']=='June 13, 2018']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
522,InterracialCupid - Interracial Dating App,DATING,3.4,212,3.0M,"50,000+",Free,0,Mature 17+,Dating,"June 13, 2018",2.3.0.1781,5.0 and up
1709,Score! Hero,GAME,4.6,5418675,96M,"100,000,000+",Free,0,Everyone,Sports,"June 13, 2018",1.751,4.4 and up
1897,Score! Hero,GAME,4.6,5419676,96M,"100,000,000+",Free,0,Everyone,Sports,"June 13, 2018",1.751,4.4 and up
2004,Score! Hero,GAME,4.6,5419676,96M,"100,000,000+",Free,0,Everyone,Sports,"June 13, 2018",1.751,4.4 and up
2102,Car Racing game for Kids - Beepzz Dogs 🐕,FAMILY,4.4,131,48M,"100,000+",Free,0,Everyone,Racing;Action & Adventure,"June 13, 2018",1.1.1,4.2 and up
2103,Pony Friends 🦄 - Beepzz racing game for kids,FAMILY,4.5,114,69M,"50,000+",Free,0,Everyone,Racing;Action & Adventure,"June 13, 2018",1.4.3,4.2 and up
2140,Shopkins World!,FAMILY,4.3,169609,34M,"10,000,000+",Free,0,Everyone,Arcade;Action & Adventure,"June 13, 2018",3.6.1,4.1 and up
2169,All-in-One Mahjong 3 FREE,FAMILY,4.5,566,17M,"50,000+",Free,0,Everyone,Board;Brain Games,"June 13, 2018",20180609,4.0 and up
2219,Shopkins World!,FAMILY,4.3,169609,34M,"10,000,000+",Free,0,Everyone,Arcade;Action & Adventure,"June 13, 2018",3.6.1,4.1 and up
2562,"Hide Something - Photo, Video",SOCIAL,4.6,225103,5.3M,"5,000,000+",Free,0,Everyone,Social,"June 13, 2018",5.1.1,4.1 and up
2766,Wanelo Shopping,SHOPPING,4.6,94205,6.5M,"1,000,000+",Free,0,Everyone,Shopping,"June 13, 2018",5.6.8,4.4 and up
2781,Wanelo Shopping,SHOPPING,4.6,94205,6.5M,"1,000,000+",Free,0,Everyone,Shopping,"June 13, 2018",5.6.8,4.4 and up
3224,GPS Status & Toolbox,TRAVEL_AND_LOCAL,4.5,149723,4.1M,"10,000,000+",Free,0,Everyone,Travel & Local,"June 13, 2018",8.1.171,4.0 and up
4100,Aldiko Book Reader,BOOKS_AND_REFERENCE,4.2,210534,22M,"10,000,000+",Free,0,Everyone,Books & Reference,"June 13, 2018",3.0.58,4.0 and up
4202,H Band,HEALTH_AND_FITNESS,4.0,214,8.9M,"10,000+",Free,0,Everyone,Health & Fitness,"June 13, 2018",3.0.2,4.4 and up
4243,NinJump,GAME,4.3,421000,36M,"10,000,000+",Free,0,Everyone,Arcade,"June 13, 2018",3.1.1,4.1 and up
4423,Planet O - Icon Pack,PERSONALIZATION,4.6,354,24M,"10,000+",Paid,$0.99,Everyone,Personalization,"June 13, 2018",1.6.1,4.1 and up
4591,Dino T-Rex,GAME,4.0,69115,2.4M,"10,000,000+",Free,0,Everyone,Arcade,"June 13, 2018",1.36,4.1 and up
4594,AT&T U-verse,FAMILY,3.7,38606,96M,"1,000,000+",Free,0,Everyone,Entertainment,"June 13, 2018",5.9.0.0031,4.1 and up
4637,Kicker U,LIFESTYLE,4.1,124,37M,"5,000+",Paid,$3.99,Everyone,Lifestyle,"June 13, 2018",3.04,4.0.3 and up
4769,Light X - Icon Pack,PERSONALIZATION,4.6,252,24M,"10,000+",Paid,$0.99,Everyone,Personalization,"June 13, 2018",1.6.1,4.1 and up
4873,Abs workout 7 minutes,HEALTH_AND_FITNESS,4.6,37224,Varies with device,"1,000,000+",Free,0,Everyone,Health & Fitness,"June 13, 2018",Varies with device,Varies with device
5226,Dash Tag - Fun Endless Runner!,FAMILY,4.5,6750,43M,"100,000+",Free,0,Everyone,Casual,"June 13, 2018",2.0.3,4.3 and up
5493,AdventureQuest Dragons,FAMILY,3.9,10114,48M,"100,000+",Free,0,Everyone,Casual,"June 13, 2018",1.0.63,4.0 and up
5527,Megatramp - a Story of Success!,FAMILY,4.3,322976,Varies with device,"5,000,000+",Free,0,Teen,Simulation,"June 13, 2018",Varies with device,4.2 and up
5536,"Egg, Inc.",FAMILY,4.7,580160,29M,"5,000,000+",Free,0,Everyone,Simulation,"June 13, 2018",1.7.5,4.0.3 and up
5604,PS4 Second Screen,FAMILY,2.4,11773,3.3M,"1,000,000+",Free,0,Everyone,Entertainment,"June 13, 2018",18.6.2,4.1 and up
5690,mon guide au bank populaire -infos et instruct...,FINANCE,NaN,4,1.5M,"1,000+",Free,0,Teen,Finance,"June 13, 2018",2,2.3 and up
6162,BG Torneos,SPORTS,NaN,7,2.3M,100+,Free,0,Everyone,Sports,"June 13, 2018",2.0.0,4.1 and up
6183,Revita.bg,HEALTH_AND_FITNESS,4.8,10,4.0M,10+,Free,0,Everyone,Health & Fitness,"June 13, 2018",3.55,4.0 and up
6460,Myjob@BM,SOCIAL,NaN,1,Varies with device,100+,Free,0,Teen,Social,"June 13, 2018",1.16.21,4.1 and up
6886,My Budget Book,FINANCE,4.7,19784,7.3M,"100,000+",Paid,$2.99,Everyone,Finance,"June 13, 2018",7.6,4.0 and up
7009,Rized ‼️ Color By Number & Pixel Coloring Book,FAMILY,3.0,1279,13M,"100,000+",Free,0,Everyone,Casual,"June 13, 2018",1.1.7,4.3 and up
7224,Ceasa CE,TOOLS,NaN,0,4.0M,50+,Free,0,Everyone,Tools,"June 13, 2018",1,4.0 and up
7514,CL Keyboard - Myanmar Keyboard (No Ads),TOOLS,5.0,24,3.2M,"5,000+",Free,0,Everyone,Tools,"June 13, 2018",1.1.3,4.3 and up
7959,"Free Professional Resume Builder, CV, Cover Le...",BUSINESS,4.2,831,11M,"50,000+",Free,0,Everyone,Business,"June 13, 2018",1.3.2.9,4.0 and up
8515,Download All Files,TOOLS,3.8,120494,2.3M,"10,000,000+",Free,0,Everyone,Tools,"June 13, 2018",2.0.7,4.1 and up
8541,Download Manager - File & Video,TOOLS,3.9,8780,5.0M,"1,000,000+",Free,0,Everyone,Tools,"June 13, 2018",2.7.5,4.2 and up
8581,Ramdor DM Mobile,BUSINESS,NaN,1,23M,100+,Free,0,Everyone,Business,"June 13, 2018",21 - Rel2.0,3.0 and up
8817,DS router,TOOLS,3.8,253,15M,"50,000+",Free,0,Everyone,Tools,"June 13, 2018",1.1.8,4.1 and up
8822,Simple x3DS Emulator - BETA,GAME,NaN,0,Varies with device,"50,000+",Free,0,Everyone,Arcade,"June 13, 2018",Varies with device,Varies with device
9123,ONEC DZ,FAMILY,NaN,40,3.1M,"1,000+",Free,0,Everyone,Education,"June 13, 2018",4,4.0.3 and up
9137,quran-DZ,SOCIAL,NaN,0,6.2M,10+,Free,0,Teen,Social,"June 13, 2018",1.1,4.2 and up
9237,EC MANAGER,VIDEO_PLAYERS,NaN,2,17M,100+,Free,0,Everyone,Video Players & Editors,"June 13, 2018",8.3.13.6,4.1 and up
9546,El Nuevo Día,NEWS_AND_MAGAZINES,4.1,8011,13M,"500,000+",Free,0,Everyone 10+,News & Magazines,"June 13, 2018",4.11.2,4.1 and up
9750,ER Blood Draw Doctor & Surgeon,FAMILY,4.0,154,58M,"50,000+",Free,0,Teen,Educational,"June 13, 2018",1.8,4.0.3 and up
9765,ER Doctor Kids Emergency Room,FAMILY,3.1,4798,30M,"500,000+",Free,0,Teen,Casual,"June 13, 2018",1.9,4.0.3 and up
9773,ER Doctor City Emergency - Surgery City Doc FREE,FAMILY,3.9,1909,84M,"100,000+",Free,0,Teen,Educational,"June 13, 2018",2.1,4.0.3 and up
10128,EZ Thanks,BUSINESS,3.2,116,Varies with device,"10,000+",Free,0,Everyone,Business,"June 13, 2018",Varies with device,Varies with device
10298,FD Calculator | Term Deposit | Fixed Deposit,FINANCE,4.8,12,2.7M,"1,000+",Free,0,Everyone,Finance,"June 13, 2018",2.1,5.0 and up
10624,Employ Florida Mobile,BUSINESS,2.9,97,9.9M,"10,000+",Free,0,Everyone,Business,"June 13, 2018",4.5.9,4.0.3 and up
10812,Fr Agnel Pune,FAMILY,4.1,80,13M,"1,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up

- Filtered out apps that last updated on june 13 2018

In [18]:
df[(df['Last Updated']=='June 13, 2018') & (df['Rating']>4)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1709,Score! Hero,GAME,4.6,5418675,96M,"100,000,000+",Free,0,Everyone,Sports,"June 13, 2018",1.751,4.4 and up
1897,Score! Hero,GAME,4.6,5419676,96M,"100,000,000+",Free,0,Everyone,Sports,"June 13, 2018",1.751,4.4 and up
2004,Score! Hero,GAME,4.6,5419676,96M,"100,000,000+",Free,0,Everyone,Sports,"June 13, 2018",1.751,4.4 and up
2102,Car Racing game for Kids - Beepzz Dogs 🐕,FAMILY,4.4,131,48M,"100,000+",Free,0,Everyone,Racing;Action & Adventure,"June 13, 2018",1.1.1,4.2 and up
2103,Pony Friends 🦄 - Beepzz racing game for kids,FAMILY,4.5,114,69M,"50,000+",Free,0,Everyone,Racing;Action & Adventure,"June 13, 2018",1.4.3,4.2 and up
2140,Shopkins World!,FAMILY,4.3,169609,34M,"10,000,000+",Free,0,Everyone,Arcade;Action & Adventure,"June 13, 2018",3.6.1,4.1 and up
2169,All-in-One Mahjong 3 FREE,FAMILY,4.5,566,17M,"50,000+",Free,0,Everyone,Board;Brain Games,"June 13, 2018",20180609,4.0 and up
2219,Shopkins World!,FAMILY,4.3,169609,34M,"10,000,000+",Free,0,Everyone,Arcade;Action & Adventure,"June 13, 2018",3.6.1,4.1 and up
2562,"Hide Something - Photo, Video",SOCIAL,4.6,225103,5.3M,"5,000,000+",Free,0,Everyone,Social,"June 13, 2018",5.1.1,4.1 and up
2766,Wanelo Shopping,SHOPPING,4.6,94205,6.5M,"1,000,000+",Free,0,Everyone,Shopping,"June 13, 2018",5.6.8,4.4 and up
2781,Wanelo Shopping,SHOPPING,4.6,94205,6.5M,"1,000,000+",Free,0,Everyone,Shopping,"June 13, 2018",5.6.8,4.4 and up
3224,GPS Status & Toolbox,TRAVEL_AND_LOCAL,4.5,149723,4.1M,"10,000,000+",Free,0,Everyone,Travel & Local,"June 13, 2018",8.1.171,4.0 and up
4100,Aldiko Book Reader,BOOKS_AND_REFERENCE,4.2,210534,22M,"10,000,000+",Free,0,Everyone,Books & Reference,"June 13, 2018",3.0.58,4.0 and up
4243,NinJump,GAME,4.3,421000,36M,"10,000,000+",Free,0,Everyone,Arcade,"June 13, 2018",3.1.1,4.1 and up
4423,Planet O - Icon Pack,PERSONALIZATION,4.6,354,24M,"10,000+",Paid,$0.99,Everyone,Personalization,"June 13, 2018",1.6.1,4.1 and up
4637,Kicker U,LIFESTYLE,4.1,124,37M,"5,000+",Paid,$3.99,Everyone,Lifestyle,"June 13, 2018",3.04,4.0.3 and up
4769,Light X - Icon Pack,PERSONALIZATION,4.6,252,24M,"10,000+",Paid,$0.99,Everyone,Personalization,"June 13, 2018",1.6.1,4.1 and up
4873,Abs workout 7 minutes,HEALTH_AND_FITNESS,4.6,37224,Varies with device,"1,000,000+",Free,0,Everyone,Health & Fitness,"June 13, 2018",Varies with device,Varies with device
5226,Dash Tag - Fun Endless Runner!,FAMILY,4.5,6750,43M,"100,000+",Free,0,Everyone,Casual,"June 13, 2018",2.0.3,4.3 and up
5527,Megatramp - a Story of Success!,FAMILY,4.3,322976,Varies with device,"5,000,000+",Free,0,Teen,Simulation,"June 13, 2018",Varies with device,4.2 and up
5536,"Egg, Inc.",FAMILY,4.7,580160,29M,"5,000,000+",Free,0,Everyone,Simulation,"June 13, 2018",1.7.5,4.0.3 and up
6183,Revita.bg,HEALTH_AND_FITNESS,4.8,10,4.0M,10+,Free,0,Everyone,Health & Fitness,"June 13, 2018",3.55,4.0 and up
6886,My Budget Book,FINANCE,4.7,19784,7.3M,"100,000+",Paid,$2.99,Everyone,Finance,"June 13, 2018",7.6,4.0 and up
7514,CL Keyboard - Myanmar Keyboard (No Ads),TOOLS,5.0,24,3.2M,"5,000+",Free,0,Everyone,Tools,"June 13, 2018",1.1.3,4.3 and up
7959,"Free Professional Resume Builder, CV, Cover Le...",BUSINESS,4.2,831,11M,"50,000+",Free,0,Everyone,Business,"June 13, 2018",1.3.2.9,4.0 and up
9546,El Nuevo Día,NEWS_AND_MAGAZINES,4.1,8011,13M,"500,000+",Free,0,Everyone 10+,News & Magazines,"June 13, 2018",4.11.2,4.1 and up
10298,FD Calculator | Term Deposit | Fixed Deposit,FINANCE,4.8,12,2.7M,"1,000+",Free,0,Everyone,Finance,"June 13, 2018",2.1,5.0 and up
10812,Fr Agnel Pune,FAMILY,4.1,80,13M,"1,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up

- filtered out apps that last updated on june 13 2018 and have rating greater than 4

### Selecting Rows

- Selecting Single Row

In [19]:
df.iloc[100]

App               Natural recipes for your beauty
Category                                   BEAUTY
Rating                                        4.7
Reviews                                      1150
Size                                         9.8M
Installs                                 100,000+
Type                                         Free
Price                                           0
Content Rating                           Everyone
Genres                                     Beauty
Last Updated                         May 15, 2018
Current Ver                                     4
Android Ver                            4.1 and up
Name: 100, dtype: object

- Selecting multiple rows

In [20]:
df.iloc[20:25]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450,14M,"100,000+",Free,0,Everyone,Art & Design,"April 20, 2018",4,4.1 and up
21,Boys Photo Editor - Six Pack & Men's Suit,ART_AND_DESIGN,4.1,654,12M,"100,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.1,4.0.3 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
23,Mcqueen Coloring pages,ART_AND_DESIGN,NaN,61,7.0M,"100,000+",Free,0,Everyone,Art & Design;Action & Adventure,"March 7, 2018",1.0.0,4.1 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up

- locate specific  row along with column

In [21]:
df.loc[55,'Category']

'AUTO_AND_VEHICLES'

### Renaming Column Name

- renamed but it only applicable for this cell. to make it permanent  use  "inplace=True"

In [ ]:
df.rename(columns={"Current Ver":"Latest Version"})

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Latest Version,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

- Now make it permanent

In [25]:
df.rename(columns={"Current Ver":"Latest Version"},inplace=True)
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Latest Version,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [27]:
df['Category'].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [32]:
df['Genres'].value_counts()

Genres
Tools                       842
Entertainment               623
Education                   549
Medical                     463
Business                    460
                           ...
Strategy;Education            1
Racing;Pretend Play           1
Communication;Creativity      1
February 11, 2018             1
Strategy;Creativity           1
Name: count, Length: 120, dtype: int64

In [35]:
df['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
552k                     1
885k                     1
1020k                    1
582k                     1
619k                     1
Name: count, Length: 462, dtype: int64